### ISSUE TITLE
DepenizenBungee potentially OOMing after repeated days of use

### ISSUE THREAD

**Issue by mergu** [DenizenScript/DepenizenBungee#1]
Apologies if this is in the wrong spot, will move if necessary. We've been running into an issue where Depenizen Bungee <-> Depenizen will lose connection because of an OOM Exception:

```
21:18:38 [SEVERE] java.lang.OutOfMemoryError: Direct buffer memory
21:18:38 [SEVERE]       at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
21:18:38 [SEVERE]       at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
21:18:38 [SEVERE]       at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
21:18:38 [SEVERE]       at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:768)
21:18:38 [SEVERE]       at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:758)
21:18:38 [SEVERE]       at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:260)
21:18:38 [SEVERE]       at io.netty.buffer.PoolArena.allocate(PoolArena.java:232)
21:18:38 [SEVERE]       at io.netty.buffer.PoolArena.reallocate(PoolArena.java:396)
21:18:38 [SEVERE]       at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:120)
21:18:38 [SEVERE]       at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:295)
21:18:38 [SEVERE]       at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:274)
21:18:38 [SEVERE]       at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1096)
21:18:38 [SEVERE]       at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
21:18:38 [SEVERE]       at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1080)
21:18:38 [SEVERE]       at com.denizenscript.depenizen.bungee.DepenizenConnection.channelRead(DepenizenConnection.java:133)
21:18:38 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
21:18:38 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
21:18:38 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
21:18:38 [SEVERE]       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
21:18:38 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
21:18:38 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
21:18:38 [SEVERE]       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
21:18:38 [SEVERE]       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
21:18:38 [SEVERE]       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
21:18:38 [SEVERE]       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
21:18:38 [SEVERE]       at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
21:18:38 [SEVERE]       at java.base/java.lang.Thread.run(Thread.java:834)
```

Our setup has people get kicked to a lobby if the main server connection ends, and a Denizen script there that sends the player back to the main server if it's alive. We do this to be able to restart the main server for plugin updates without forcing players to log out.

When this OOM issue starts, people get repeatedly kicked between the main server and lobby several times. People seem to report it happens when teleporting to a new world, though I've never been able to reliably replicate.

Exception thrown on the actual server:
```
[15:49:02] [nioEventLoopGroup-2-3/INFO]:  ERROR!
     Error Message: Internal exception was thrown!
[Error Continued] java.io.IOException: Connection reset by peer
[Error Continued] java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[Error Continued] java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
[Error Continued] java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
[Error Continued] java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
[Error Continued] java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
[Error Continued] java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
[Error Continued] io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
[Error Continued] io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
[Error Continued] io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
[Error Continued] io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
[Error Continued] io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[Error Continued] io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547)
[Error Continued] io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501)
[Error Continued] io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[Error Continued] io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[Error Continued] io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[Error Continued] java.base/java.lang.Thread.run(Thread.java:834)

[15:49:02] [nioEventLoopGroup-2-3/INFO]: +> [BungeeClient...] Depenizen-Bungee connection ended. 
[15:49:09] [Server thread/INFO]: +> [] Depenizen now connected to Bungee server.
```

I will note - I have not updated to the changes made today. I can't see those fixing this issue, and the issue takes several days to start occurring so I'm going to update but I don't want to run into this again. Restarting the proxy fixes the issue but I would rather not take the proxy down.

I can post more logs if needed

**Comment by mcmonkey4eva** [comment]
I imagine this might be a memory leak caused by netty buffers, which very helpfully do not obey any of java's memory management rules, and thus could very easily have been improperly handled somewhere.

Would be very useful to get some form of Java memory profiling or a heapdump to track down what memory exactly is filling up.

**Comment by mcmonkey4eva** [comment]
Pushed a set of updates to both DepenizenBungee and Depenizen that might fix this issue (not guaranteed but *might*).
Assuming it's the actual buffer being reported in the stacktrace that's at fault, it might be that netty doesn't clear already-read space, even when rebuilding the underlying buffer to adjust for capacity (which I would have assumed it would do). If it doesn't do that, the commits made will fix that by way of reallocating the buffer entirely quite regularly.

**Comment by mergu** [comment]
Thank you. I'll update and re-open if the issue persists
